# Generated by Django 4.2.27 on 2025-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['namespace', 'short_code'], name='urls_shortu_namespa_75f1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['namespace', '-created_at'], name='urls_shortu_namespa_bff8af_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='urls_shortu_short_c_4140e7_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['-created_at'], name='urls_shortu_created_3c25f4_idx'),
        ),
    ]
