# Generated by Django 4.2.27 on 2025-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_shorturl_urls_shortu_namespa_75f1a5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shorturl',
            name='urls_shortu_namespa_75f1a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='shorturl',
            name='urls_shortu_short_c_4140e7_idx',
        ),
        migrations.AlterUniqueTogether(
            name='shorturl',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='original_url',
            field=models.URLField(max_length=2048, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='short_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
