# Generated by Django 4.2.27 on 2025-12-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namespaces', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='namespace',
            index=models.Index(fields=['name'], name='namespaces__name_8eeb8c_idx'),
        ),
        migrations.AddIndex(
            model_name='namespace',
            index=models.Index(fields=['organization', '-created_at'], name='namespaces__organiz_50678a_idx'),
        ),
    ]
